
class Mysql5p7:
    TINYINT = "TINYINT"
    SMALLINT = "SMALLINT"
    MEDIUMINT = "MEDIUMINT"
    INTEGER = "INTEGER"
    # INT = "INTEGER"
    BIGINT = 'BIGINT'

    FLOAT = "FLOAT"
    DOUBLE = "DOUBLE"

    DECIMAL = "DECIMAL"
    # DEC = "DECIMAL"

    DATE = "DATE"
    TIME = "TIME"
    YEAR = "YEAR"
    DATETIME = "DATETIME"
    TIMESTAMP = "TIMESTAMP"

    CHAR = "CHAR"
    VARCHAR = "VARCHAR"

    TINYBLOB = "TINYBLOB"
    BLOB = "BLOB"
    MEDIUMBLOB = "MEDIUMBLOB"
    LONGBLOB = "LONGBLOB"

    TINYTEXT = "TINYTEXT"
    TEXT = "TEXT"
    MEDIUMTEXT = "MEDIUMTEXT"
    LONGTEXT = "LONGTEXT"
